### ISSUE TITLE
Consider Graal native image for CLI

### ISSUE THREAD

**Issue by uweschaefer** [Mercateo/factcast#224]
**Is your feature request related to a problem? Please describe.**
it would be great to provide a native image to help with startup latency

**Comment by uweschaefer** [comment]
Obviously, the spring boot mechanics prevent this currently:
```
[org.factcast.client.grpc.cli.cli:4599]     analysis:  28,517.38 ms
error: unsupported features in 14 methods
Detailed message:
Error: Bytecode parsing error: java.lang.NoClassDefFoundError: org/springframework/web/context/support/GenericWebApplicationContext
Trace: 
	at parsing org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:591)
Call path from entry point to org.springframework.boot.SpringApplication.createApplicationContext(): 
	at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:586)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.factcast.client.grpc.cli.CLI.main(CLI.java:48)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original exception that caused the problem: java.lang.NoClassDefFoundError: org/springframework/web/context/support/GenericWebApplicationContext
```

It should be possible to get rid of spring boot entirely in this project, so that another attempt at graal makes sense.

**Comment by uweschaefer** [comment]
postponed to 0.2
